---

- name: Setup User Group
  group: name={{ runtime_user }} system=yes

- name: Setup User
  user: name={{ runtime_user }} group={{ runtime_user }} system=yes

- name: Setup WorkDir
  file: path={{ item }} state=directory owner={{ runtime_user }} group={{ runtime_user }}
  with_items:
  - "{{ runtime_workdir }}"
  - "{{ runtime_workdir }}/bin"

- name: Install Dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items: "{{ runtime_dependencies }}"
  when: item != ""

- name: Setup Dest Dirs
  file: path={{ item.destdir }} state=directory
  with_items: "{{ runtime_files }}"
  when: item.destdir is defined

- name: Setup Files
#  copy: src={{ item.src }} dest={{ item.dest }} owner={{ runtime_user }} group={{ runtime_user }} mode={{ item.mode }}
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  with_items: "{{ runtime_files }}"
  notify: restart service

## TODO dependancies reload/restart on file change ? (Nginx ?)

- name: Setup systemctl script
  template: src=binary.service dest=/lib/systemd/system/{{ application_name }}.service
  notify: systemctl daemon-reload

- name: Enable & Start Service
  service: name={{ application_name }} state=started enabled=yes
