---

- name: Install Services
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items: runtime_services
  when: item != ""

- name: Setup Dest Dirs
  file: path={{ item.destdir }} state=directory
  with_items: runtime_services_files
  when: item.destdir is defined

- name: Setup Files
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode={{ item.mode }}
  with_items: runtime_services_files
  when: item.src is defined
  register: runtime_services_files_installed

- name: Restart Needed Services
  service: name={{ item.service }} state=restarted
  with_items: runtime_services_files_installed.results
